/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EstadoRouteImport } from './routes/estado'
import { Route as JogosRouteImport } from './routes/jogos'
import { Route as PartidasIndexRouteImport } from './routes/partidas/index'
import { Route as PartidasIdRouteImport } from './routes/partidas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadoRoute = EstadoRouteImport.update({
  id: '/estado',
  path: '/estado',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosRoute = JogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidasIndexRoute = PartidasIndexRouteImport.update({
  id: '/partidas/',
  path: '/partidas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidasIdRoute = PartidasIdRouteImport.update({
  id: '/partidas/$id',
  path: '/partidas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estado': typeof EstadoRoute
  '/jogos': typeof JogosRoute
  '/partidas/$id': typeof PartidasIdRoute
  '/partidas/': typeof PartidasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estado': typeof EstadoRoute
  '/jogos': typeof JogosRoute
  '/partidas/$id': typeof PartidasIdRoute
  '/partidas': typeof PartidasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/estado': typeof EstadoRoute
  '/jogos': typeof JogosRoute
  '/partidas/$id': typeof PartidasIdRoute
  '/partidas/': typeof PartidasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/estado' | '/jogos' | '/partidas/$id' | '/partidas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/estado' | '/jogos' | '/partidas/$id' | '/partidas'
  id: '__root__' | '/' | '/estado' | '/jogos' | '/partidas/$id' | '/partidas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstadoRoute: typeof EstadoRoute
  JogosRoute: typeof JogosRoute
  PartidasIdRoute: typeof PartidasIdRoute
  PartidasIndexRoute: typeof PartidasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estado': {
      id: '/estado'
      path: '/estado'
      fullPath: '/estado'
      preLoaderRoute: typeof EstadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos': {
      id: '/jogos'
      path: '/jogos'
      fullPath: '/jogos'
      preLoaderRoute: typeof JogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidas/': {
      id: '/partidas/'
      path: '/partidas'
      fullPath: '/partidas/'
      preLoaderRoute: typeof PartidasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidas/$id': {
      id: '/partidas/$id'
      path: '/partidas/$id'
      fullPath: '/partidas/$id'
      preLoaderRoute: typeof PartidasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstadoRoute: EstadoRoute,
  JogosRoute: JogosRoute,
  PartidasIdRoute: PartidasIdRoute,
  PartidasIndexRoute: PartidasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
